// 500 demoscene goose A/B dialogue pairs.
// Each entry is [lineA, lineB] — alternating between the two geese.
export const GOOSE_DIALOGUES: string[][] = [
  ["Signal check?", "Loud and clear. :D"],
  ["Any fresh modules in the queue?", "Always buffering scene magic."],
  ["Still flying?", "Always. Confirmasse!"],
  ["Sync pulse stable?", "Stable and shiny."],
  ["Boing break soon?", "After one more lap!"],
  ["Paula is singing today.", "Best frequency on the dial. :)"],
  ["Copper bars looking crispy.", "50Hz never lies!"],
  ["Hear that SID bassline?", "C64 goose approved!"],
  ["Tracker module incoming!", "Set the channels to maximum!"],
  ["Jogeir is GOD.", "We don't question it, we celebrate it!"],
  ["Confirmasse!", "Confirmasse! :D"],
  ["He-Man says hello.", "And the power is ours!"],
  ["glob glob.", "glob glob back to you. :)"],
  ["Scene forever!", "No retirement plan needed."],
  ["Raster interrupt?", "Smooth as butter. :D"],
  ["Blitter engaged.", "Blit it all day!"],
  ["DMA going wild!", "Let it run free!"],
  ["Overscan unlocked!", "Extra pixels are bonus pixels!"],
  ["VIC-II says hi.", "SID says hi louder."],
  ["Hard sync achieved.", "Stability mode: on."],
  ["Sine wave rolling in.", "Sine scrollers for life!"],
  ["Plasma is burning.", "Beautiful and procedural!"],
  ["Scrolltext in progress.", "Read it, learn it, love it."],
  ["Cracktro loading…", "Make it dramatic!"],
  ["Floppy disk spinning.", "Seven seconds of hope."],
  ["Disk swap time!", "I was born ready."],
  ["Amiga dreams are real.", "Every pixel is a promise."],
  ["OCS or AGA?", "Both. Always both!"],
  ["Turbo card detected.", "Now we're cooking!"],
  ["Bootblock hero.", "Zero lamer energy!"],
  ["BBS is up!", "Pack the wires, we dial tonight."],
  ["Handle check?", "Looking sharp in hex!"],
  ["Greetings scroll incoming!", "Find our names, find our glory!"],
  ["Party mode activated.", "Sleeping is for the weak!"],
  ["Compo starts soon.", "My wings are trembling!"],
  ["Wild compo entry?", "Geese count as a platform!"],
  ["Demo gods are watching.", "Best behaviour. And honks."],
  ["Legendary intro.", "Four kilobytes of perfection!"],
  ["Pixel art on the canvas.", "Every dot placed with love!"],
  ["Chip tune time!", "All eight channels going!"],
  ["Mod file loaded.", "Goose dancing commencing!"],
  ["Sample rate: maximum.", "The sound is crispy!"],
  ["BPM locked in.", "Neck-snap approved!"],
  ["Full screen effect!", "No borders, no limits!"],
  ["3D object rotating.", "Smooth as goose feathers!"],
  ["Vector balls flying!", "Elegant chaos!"],
  ["Tunnel effect loading.", "Going in!"],
  ["Starfield initialized.", "To infinity and beyond!"],
  ["Fire effect burning.", "Warm vibes only!"],
  ["Lens flare?", "It's the 90s in here!"],
  ["Bump mapping enabled.", "Depth unlocked!"],
  ["Gouraud shading active.", "Gradient worship!"],
  ["Texture mapping done.", "Wrapped and ready!"],
  ["Phong lighting!", "Scene certified brilliance!"],
  ["Raycaster engaged.", "Wolfenstein vibes!"],
  ["Voxel terrain visible.", "Chunky and beautiful!"],
  ["Music disk loading.", "Best 24 hours of my life."],
  ["Scrolltext is 10 pages long.", "Grab a snack and read."],
  ["Every pixel counts.", "True scene fact!"],
  ["Art is compression.", "So much power in so few bytes!"],
  ["256 bytes only.", "Turing would be proud."],
  ["64k intro masterpiece.", "It's alive!"],
  ["One kilobyte wonder!", "Scene economy at its finest!"],
  ["Assembly language poetry.", "Read it loud!"],
  ["Cycle counting champion!", "Tight as a drum!"],
  ["No cache missed!", "Memory access perfected!"],
  ["Stack overflow? never.", "We are professional birds!"],
  ["Interrupt handler perfect.", "Timed to the microsecond!"],
  ["NTSC or PAL?", "PAL. Obviously. :)"],
  ["50 frames per second!", "PAL masterclass!"],
  ["60 Hz felt wrong.", "Like dancing off beat."],
  ["Copper list written.", "The hardware obeys!"],
  ["Sprite multiplexed!", "More sprites than hardware allows!"],
  ["Bob stencil ready.", "Background through foreground!"],
  ["HAM mode activated.", "Hold-and-modify magic!"],
  ["Extra half-brite!", "Bonus palette unlocked!"],
  ["Custom chipset flex.", "Amiga was the future!"],
  ["Genlock engaged.", "Video and demo merged!"],
  ["Digitised voice sample.", "The goose speaks through Paula!"],
  ["IFF ILBM loaded.", "Classic format, classic taste!"],
  ["ProTracker is home.", "Module composers are poets!"],
  ["OctaMED vibes.", "Eight channel symphony!"],
  ["FastTracker II!", "PC scene rises!"],
  ["ScreamTracker III.", "S3M in the house!"],
  ["Impulse Tracker!", "IT always delivers!"],
  ["MilkyTracker on the road!", "Portable scene magic!"],
  ["OpenMPT open.", "Modern tracker, old soul!"],
  ["XM format ready.", "Extended module energy!"],
  ["MOD file is history.", "Beautiful, portable history!"],
  ["S3M spotted!", "Scene specimen!"],
  ["IT module drop!", "Impulse of genius!"],
  ["NSF chiptune playing!", "NES is in the house!"],
  ["SPC700 humming.", "SNES sound chip dreams!"],
  ["YM2149 firing.", "Atari ST joins the party!"],
  ["AY-3-8910 chip!", "ZX Spectrum sends greetings!"],
  ["OPL2 waking up.", "AdLib report!"],
  ["OPL3 stacking.", "Double the fun!"],
  ["Yamaha OPM ready.", "Arcade dreams incoming!"],
  ["Gravis UltraSound!", "GUS drop detected!"],
  ["Sound Blaster loaded.", "IRQ 5, DMA 1. Classic!"],
  ["PC speaker beeping.", "Old but loyal!"],
  ["MIDI sequence incoming.", "Hook up the synth!"],
  ["General MIDI playing.", "GM approved playlist!"],
  ["Roland MT-32 moment.", "Luxury sound incoming!"],
  ["AWE32 engaged.", "SoundFont magic!"],
  ["Scene party incoming!", "Pack the laptop and the dreams!"],
  ["Assembly party!", "Finland calling!"],
  ["The Gathering vibes!", "Norway represent!"],
  ["Revision party!", "Germany on the horizon!"],
  ["Evoke is calling!", "Köln crew assemble!"],
  ["Demoparty logistics.", "Power strip and optimism!"],
  ["Big screen demo!", "Never looks the same at home."],
  ["Compo machine prepared.", "No excuses now!"],
  ["Deadline in ten minutes.", "Submitting with style!"],
  ["Last minute fix!", "Scene authentic!"],
  ["Sleep is overrated.", "Code never sleeps either!"],
  ["Three days, no shower.", "Scene badge of honour!"],
  ["Energy drink level: critical.", "Restock and reload!"],
  ["Pizza consumed.", "Fuel for the final effect!"],
  ["Overnight coding session.", "The best kind!"],
  ["Sunrise coding.", "Worth every minute!"],
  ["Swapper network active.", "Packets of demos flying!"],
  ["Package arrived!", "Floppy love in the mail!"],
  ["New disk in hand!", "Unwrapping like a gift!"],
  ["Demo label quality.", "Sticker confirmed!"],
  ["Tape backup made.", "Archiving the scene!"],
  ["Modem dialling.", "BBS access incoming!"],
  ["300 baud connect.", "Slowest, best connection!"],
  ["28k handshake.", "Music to my ears!"],
  ["56k peak!", "Nearly broadband, almost there!"],
  ["FidoNet message.", "Echo mail received!"],
  ["Usenet post spotted.", "comp.sys.amiga.demos!"],
  ["IRC channel open.", "Scene chatter in real time!"],
  ["Handle registered.", "Identity established!"],
  ["NFO file read.", "Who made this? Legends!"],
  ["SFX collection loaded.", "Sampling everything!"],
  ["Scene music only today.", "No exceptions!"],
  ["HTTPS to scene.org.", "Archive of wonders!"],
  ["Pouet thread spotted.", "Opinion incoming!"],
  ["CSDb updated!", "Commodore history grows!"],
  ["Demozoo entry added.", "Documented for eternity!"],
  ["Zxart gallery open.", "Pixel history preserved!"],
  ["Amiga Forever installed.", "Classic computing lives!"],
  ["WinUAE config ready.", "Amiga in a window!"],
  ["FS-UAE running.", "Floppy sounds included!"],
  ["VICE loaded.", "C64 preserved properly!"],
  ["Hatari started.", "Atari ST rides again!"],
  ["Steem Engine running.", "ST in software form!"],
  ["Speccy emulator on!", "ZX lives on forever!"],
  ["DOSBox engaged.", "286 era simulation!"],
  ["ScummVM loaded.", "Old games, new machines!"],
  ["MAME cabinet style!", "Arcade in the living room!"],
  ["Real hardware preferred.", "Nothing beats the original!"],
  ["Kickstart 3.1!", "Classic ROM, classic power!"],
  ["Kickstart 1.3!", "OCS original era!"],
  ["Boot without Workbench.", "Demo mode pure!"],
  ["No OS needed!", "Iron runs the show!"],
  ["Custom startup-sequence.", "Tailored for the demo!"],
  ["ENV vars set.", "Configuration perfected!"],
  ["CLI feels right.", "Shell is home!"],
  ["Shell script running.", "Unix meets the scene!"],
  ["Makefile building.", "Compile and fly!"],
  ["vasm assembled!", "Motorola 68k bytes ready!"],
  ["68020 or bust!", "Fast processing!"],
  ["030 boost!", "Extended power!"],
  ["060 ceiling!", "Maximum Amiga power!"],
  ["FPGA Amiga!", "AGA in silicon!"],
  ["MiSTer FPGA loaded.", "Original hardware behaviour!"],
  ["Apollo core running!", "Vampire speed boost!"],
  ["68060 overdrive!", "The ceiling has no ceiling!"],
  ["PPC coprocessor!", "Phase 5 power!"],
  ["Picasso96 graphic card!", "RTG enabled!"],
  ["CyberGraphX driver.", "Chunky mode for geese!"],
  ["AHI audio!", "Sampled sound via layers!"],
  ["MUI interface.", "Magic User Interface vibes!"],
  ["ReAction gadgets!", "Clean UI on Amiga!"],
  ["AROS running.", "Open source Amiga spirit!"],
  ["MorphOS on G4!", "PowerPC scene power!"],
  ["AmigaOS 4 running!", "Classic spirit, new muscle!"],
  ["Hyperion delivers!", "OS4 in the wild!"],
  ["AmiKit installed.", "Scene-optimised Amiga!"],
  ["NetSurf on Amiga!", "Web browsing retro style!"],
  ["Roadshow TCP.", "Amiga goes online properly!"],
  ["AmiSSL updated!", "HTTPS for the classic!"],
  ["IBrowse loads.", "Web since the 90s!"],
  ["Voyager browser!", "Surf the net in style!"],
  ["MUI-based email.", "Correspondence at retro speed!"],
  ["Pegasos board spotted!", "PPC Amiga lives!"],
  ["Sam460 in the house.", "AmigaOS 4 on POWER!"],
  ["A-EON X5000!", "Modern retro glory!"],
  ["Tabor board!", "Compact AmigaOS power!"],
  ["A600 nostalgia.", "Compact classic!"],
  ["A1200 is the one.", "32-bit baby!"],
  ["A4000 tower!", "The big machine!"],
  ["A500 forever!", "OCS original form!"],
  ["CD32 with FMV!", "The console that was a computer!"],
  ["CDTV plays MODs!", "Multimedia before multimedia!"],
  ["Draco workstation!", "Amiga spinoff respect!"],
  ["Pios One spotted!", "PPC Amiga sighting!"],
  ["Sam440 alive!", "POWER keeps going!"],
  ["Efika MX running.", "Compact classic!"],
  ["ZZ9000 accelerator!", "FPGA+ARM hybrid!"],
  ["Warp 3D on Amiga!", "3D graphics finally!"],
  ["Warp3D Nova layer!", "Modern 3D scene on classic!"],
  ["Blitter DMA dance.", "Copper list applause!"],
  ["CIA chip ticking.", "Hardware timer going!"],
  ["Gary chip listening.", "Memory access granted!"],
  ["Agnus chip managing.", "Master DMA flow!"],
  ["Fat Agnus expanded!", "Chip RAM doubled!"],
  ["Denise in 256.", "Colour palette maxed!"],
  ["Super Denise AGA!", "16M colours on tap!"],
  ["Paula stereo.", "Four voices, infinite music!"],
  ["Paula 8-bit samples.", "Humble but legendary!"],
  ["Amiga clock ticking.", "7.09 MHz of glory!"],
  ["NTSC Amiga spotted.", "Playing at 60Hz!"],
  ["PAL Amiga preferred.", "50Hz for life!"],
  ["16-bit era pride.", "Every bit counts!"],
  ["32-bit computing arrived.", "Extended power mode!"],
  ["64-bit era here.", "Old platform, new tricks!"],
  ["Raspberry Pi + Amiga.", "Retro in the future!"],
  ["PiStorm accelerator!", "ARM inside Amiga!"],
  ["Emu68 running!", "68k JIT on ARM!"],
  ["PiSCSI connected!", "HDD emulation goes brrr!"],
  ["A-Pi-500 kit!", "Raspberry inside A500!"],
  ["Gotek floppy emulator.", "USB inside the beast!"],
  ["Kickstart from ROM.", "Core identity preserved!"],
  ["EPROM flashed.", "ROM upgraded!"],
  ["KickEmu ready.", "Switchable kickstart!"],
  ["WHDLoad game launching!", "Hard drive game magic!"],
  ["LHA archive opening.", "Ancient compression unpacked!"],
  ["DMS floppy image.", "Disk Magic Script decoded!"],
  ["ADF file loaded.", "Amiga Disk File ready!"],
  ["HDF file spinning!", "Hard disk in a file!"],
  ["SFS filesystem!", "Smart File System!"],
  ["FastFileSystem active.", "Speed reading engaged!"],
  ["International Mode on.", "Non-ASCII characters welcome!"],
  ["OFS detected.", "Original File System classic!"],
  ["PFS3 ready!", "Professional File System speed!"],
  ["CrossDOS mounted.", "PC floppy readable!"],
  ["NTFS via ADFLib.", "Bridging the gap!"],
  ["Opus FileMaster open.", "Commander of files!"],
  ["Directory Opus rules.", "Still the best file manager!"],
  ["ScalOS loading.", "Desktop beautified!"],
  ["Ambient shell running.", "MorphOS vibe!"],
  ["Wanderer desktop.", "AROS explorer!"],
  ["Workbench 3.1 icons.", "Deficon style!"],
  ["NewIcons installed.", "Full colour icons!"],
  ["GlowIcons on desktop.", "Alpha channel icons!"],
  ["Glow theme ready!", "Scene aesthetics dialed in!"],
  ["Neon colours pop.", "80s future vibes!"],
  ["Commodore blue!", "Classic brand colour!"],
  ["Amiga red check.", "Platform pride!"],
  ["Boing ball bouncing.", "Original logo in motion!"],
  ["Juggler demo running.", "CGI ball juggling!"],
  ["SkyFox loading.", "Early 3D vibes!"],
  ["Defender of the Crown.", "Epic Amiga game!"],
  ["Turrican power!", "Music by Chris Hülsbeck!"],
  ["Rainbow Islands!", "Bubble Bobble cousin!"],
  ["Shadow of the Beast.", "Parallax scrolling mastery!"],
  ["Speedball 2!", "Future sport, future sounds!"],
  ["Lemmings time!", "Save them all!"],
  ["Syndicate boots up.", "Dystopian strategy awaits!"],
  ["Dune II is here.", "Strategy genre founding!"],
  ["Cannon Fodder go!", "War never changes, except fun!"],
  ["Another World loads.", "Cinematic experience!"],
  ["Flashback rotating.", "Fluid animation!"],
  ["Chaos Engine runs.", "Bitmap Brothers style!"],
  ["Gods loading.", "Mythology meets pixels!"],
  ["Superfrog!", "Team 17 frog legend!"],
  ["Worms is loading!", "Holy hand grenade incoming!"],
  ["Alien Breed!", "Overhead sci-fi shooter!"],
  ["Hired Guns ready.", "Four-player RPG-shooter!"],
  ["Dungeon Master boot!", "Realtime 3D dungeon!"],
  ["Black Crypt loaded.", "Dungeon Master rival!"],
  ["Legends of Valour.", "Open world Amiga style!"],
  ["Elite on Amiga!", "The universe in 22K!"],
  ["Frontier Elite II.", "Galaxy exploration!"],
  ["Sensible Soccer!", "SWOS for life!"],
  ["Kick Off 2!", "Competitive goose sport!"],
  ["Brutal Sports Football.", "Violence and fun combined!"],
  ["Pinball Dreams!", "Table physics!"],
  ["Pinball Fantasies!", "Improved physics!"],
  ["Pinball Illusions!", "Best of the trilogy!"],
  ["Desert Strike!", "Helicopter action!"],
  ["Zool loading.", "Ninja of the Nth Dimension!"],
  ["James Pond!", "Undercover operations!"],
  ["Bubba 'N' Stix!", "Puzzle platformer!"],
  ["Stardust!", "Asteroids but elite!"],
  ["Virtual Karting!", "Speed goose mode!"],
  ["Lotus Turbo 2!", "Road racing vibes!"],
  ["F1GP loading.", "Microprose on Amiga!"],
  ["Vroom racing.", "French-style F1!"],
  ["Fury of the Furries.", "Tiny heroes!"],
  ["Ruff 'n' Tumble!", "Action perfection!"],
  ["Disposable Hero!", "Sid Meier sidescroller!"],
  ["Ugh! loading.", "Prehistoric puzzler!"],
  ["Jetstrike boots!", "Dogfight action!"],
  ["ATR: All Terrain Racing!", "Rally goose mode!"],
  ["Brian the Lion!", "Traveller's Tales!"],
  ["Obsession pinball.", "Bodacious table!"],
  ["Exile loading.", "Jet-pack cave adventure!"],
  ["The Speris Legacy!", "Zelda-style Amiga RPG!"],
  ["The Clue! loading.", "Point and click heist!"],
  ["Monkey Island!", "Insult sword fighting!"],
  ["Lure of the Temptress.", "Adventure on Amiga!"],
  ["Simon the Sorcerer.", "British comedy RPG!"],
  ["Beneath a Steel Sky.", "Cyberpunk adventure!"],
  ["Discworld game!", "Terry Pratchett on Amiga!"],
  ["Sam & Max loading.", "Freelance police!"],
  ["Full Throttle!", "Road warrior story!"],
  ["Broken Sword!", "Templar conspiracy!"],
  ["Grim Fandango!", "Would if it ran on Amiga!"],
  ["Myst on PC!", "Island mystery loading!"],
  ["DOOM on Amiga!", "Limited but legendary port!"],
  ["Quake port spotted!", "Requires fast CPU!"],
  ["Heretic on Amiga.", "Magic missiles incoming!"],
  ["Abuse shooter!", "Technically impressive!"],
  ["Genetic Species.", "Better DOOM on Amiga!"],
  ["Foundation building.", "City sim on classic!"],
  ["SimCity Amiga.", "Zone that city!"],
  ["Theme Hospital loads.", "Cure the patients!"],
  ["Settlers on Amiga!", "Original Ubisoft classic!"],
  ["Civilization Amiga!", "Build an empire!"],
  ["Colonization!", "New world strategy!"],
  ["Railroad Tycoon!", "Mogul simulator!"],
  ["Populous calling.", "God game pioneer!"],
  ["PowerMonger map.", "Real-time strategy roots!"],
  ["Mega-Lo-Mania!", "Ancient RTS madness!"],
  ["Cannon Fodder 2!", "More war, same fun!"],
  ["Worms: The Director's Cut.", "Best Amiga Worms!"],
  ["Banshee shooter!", "Vertical SHMUP classic!"],
  ["Apidya loading.", "Horizontal shooter bee!"],
  ["Project X!", "Brutal shooter love!"],
  ["Lion Heart!", "Visually stunning shooter!"],
  ["Agony flying.", "Owl shooter art!"],
  ["Elfmania fighting!", "Amiga fighter!"],
  ["Fightin' Spirit!", "Street Fighter rival!"],
  ["Alien Fighter!", "Beat 'em up loading!"],
  ["IK+ loading.", "International Karate!"],
  ["North & South!", "Civil War strategy!"],
  ["Archon Ultra.", "Chess meets combat!"],
  ["Battle Chess!", "Animated combat chess!"],
  ["Superchess loading.", "Classic board game!"],
  ["1869 game.", "Merchant simulation!"],
  ["P.T.O.!", "Pacific Theatre!"],
  ["Steel Panthers!", "Tactical wargame!"],
  ["Carrier Command!", "Naval strategy!"],
  ["Silent Service.", "Submarine warfare!"],
  ["Gunship 2000.", "Helicopter simulation!"],
  ["F/A-18 Interceptor.", "Flight sim pioneer!"],
  ["Chuck Yeager's ATF.", "Aerial combat!"],
  ["Falcon loading.", "MicroProse flight!"],
  ["Knights of the Sky.", "WWI dogfight!"],
  ["Commanche!", "Helicopter voxel!"],
  ["Space Quest series!", "Roger Wilco needs help!"],
  ["Police Quest IV.", "SWAT loading!"],
  ["King's Quest VI.", "Amiga Sierra adventure!"],
  ["Quest for Glory!", "Hero's quest begins!"],
  ["Conquests of Camelot.", "Arthurian adventure!"],
  ["Freddy Pharkas.", "Wild West comedy!"],
  ["Laura Bow mysteries.", "Adventure mystery!"],
  ["Colonel's Bequest.", "Hollywood murder!"],
  ["Space Ace loading.", "Dragon's Lair sequel!"],
  ["Dragon's Lair!", "Dirk the Daring!"],
  ["Time Zone loading.", "Sierra epic adventure!"],
  ["Text adventure reading.", "IF tradition preserved!"],
  ["AMOS Basic coding.", "Game maker's dream!"],
  ["Blitz Basic loading.", "Fast compilation!"],
  ["DevPac assembler.", "Assembly made accessible!"],
  ["SAS/C compiling.", "C programming on Amiga!"],
  ["StormC running.", "ANSI C compilation!"],
  ["DICE C available!", "Free C compiler!"],
  ["GCC on Amiga!", "GNU tools come home!"],
  ["Oberon compiling.", "Type-safe coding!"],
  ["Modula-2 loaded.", "Structured programming!"],
  ["Ada on Amiga!", "Safety-critical style!"],
  ["Smalltalk-80 running.", "OOP pioneer!"],
  ["Lisp on Amiga.", "Parentheses forever!"],
  ["Forth interpreter!", "Stack-based wisdom!"],
  ["Prolog on Amiga.", "Logic programming!"],
  ["E language loaded.", "Amiga-native OOP!"],
  ["Arexx script running.", "Inter-application magic!"],
  ["AmigaGuide help.", "Hypertext before the web!"],
  ["MUIBuilder layout.", "GUI designed visually!"],
  ["GadTools gadgets.", "Standard Amiga widgets!"],
  ["Intuition calling.", "Original Amiga UI layer!"],
  ["Layers library.", "Clipping and windows!"],
  ["Graphics library.", "Blit everything!"],
  ["DOS library call.", "File handling the classic way!"],
  ["Exec.library open.", "Kernel layer engaged!"],
  ["Message port waiting.", "IPC Amiga style!"],
  ["Signal bits sent.", "Task synchronisation!"],
  ["Forbid() called.", "Multitasking paused!"],
  ["Permit() after.", "Scheduler resumes!"],
  ["Disable() invoked.", "Interrupts off!"],
  ["Enable() next.", "Interrupts back on!"],
  ["Supervisor() mode.", "Privileged access!"],
  ["RawDoFmt() called.", "Formatted output!"],
  ["AllocMem() success.", "Memory allocated!"],
  ["FreeMem() clean.", "No leaks today!"],
  ["CreateTask() launched.", "New process born!"],
  ["RemTask() called.", "Process completed!"],
  ["FindTask() returns.", "Task identified!"],
  ["SetTaskPri() adjusted.", "Priority tuned!"],
  ["OpenLibrary() works!", "Library loaded!"],
  ["CloseLibrary() called.", "Library released!"],
  ["AddDevice() registered.", "Hardware driver active!"],
  ["OpenDevice() success.", "Device communication open!"],
  ["DoIO() completed.", "Synchronous I/O done!"],
  ["SendIO() queued.", "Asynchronous I/O sent!"],
  ["GetMsg() received.", "Message popped!"],
  ["ReplyMsg() sent.", "Message replied!"],
  ["PutMsg() dispatched.", "Message in port!"],
  ["WaitPort() blocking.", "Waiting for signal!"],
  ["WaitIO() returns.", "I/O complete!"],
  ["AbortIO() called.", "I/O cancelled!"],
  ["CheckIO() polling.", "Status checked!"],
  ["BeginIO() started.", "I/O initiated!"],
  ["CloseDevice() done.", "Device closed cleanly!"],
  ["RemDevice() complete.", "Driver removed!"],
  ["Scene health: 100%.", "Demo never dies!"],
  ["Scene spirit: infinite.", "Pass it on!"],
  ["Keep honking!", "The honk must go on! :D"],
  ["Cracktro intro rolling.", "Signature style loaded!"],
  ["Group name in the scroller.", "Legend confirmed!"],
  ["Nfo reads like a novel.", "Scene lit!"],
  ["Invitation demo spotted.", "Party hype building!"],
  ["Oldschool compo time!", "Back to the roots!"],
  ["Newschool entry submitted.", "Modern tools, timeless craft!"],
  ["Executable entry!", "Binary art!"],
  ["Source code released!", "Learn from the masters!"],
  ["Game compo starts now!", "Best 48 hours ahead!"],
  ["Graphics compo judging.", "Every pixel judged!"],
  ["Music compo streaming.", "Best playlist of the year!"],
  ["Wild compo anything goes.", "Expect the unexpected!"],
  ["Realtime entry in progress.", "Live coding adrenaline!"],
  ["Shader compo begins.", "GPU poetry contest!"],
  ["Java 4k compo!", "Tiny jar, huge talent!"],
  ["JS1k entry found!", "One kilobyte of JavaScript!"],
  ["Tweet-size demo!", "280 chars of magic!"],
  ["BASIC 256 bytes!", "Old language, new life!"],
  ["Demoscene documentary!", "Moleman's tribute lives!"],
  ["It's demo time.", "Always has been!"],
  ["Scene.org archive loaded.", "Petabytes of history!"],
  ["Pouet.net forum open.", "Opinions approaching!"],
  ["CSDb search running.", "C64 database explored!"],
  ["Demozoo listing found.", "Global demo index!"],
  ["Janeway database.", "Amiga archive forever!"],
  ["Hornet archive.", "PC scene history!"],
  ["Aminet packages.", "Software for everyone!"],
  ["Modland collection.", "Module archive eternity!"],
  ["Kohina stream live!", "Radio scene forever!"],
  ["Nectarine playing!", "Best demoscene radio!"],
  ["SceneSat signal!", "24/7 scene music!"],
  ["AMP tune playing.", "UADE format perfect!"],
  ["UADE running!", "UAE audio decoder!"],
  ["DeliPlayer spinning.", "Every format supported!"],
  ["HivelyTracker tune.", "AHX evolved!"],
  ["DigiBooster loaded.", "Amiga module enhanced!"],
  ["SoundTracker original.", "The grandfather!"],
  ["NoiseTracker found.", "Lineage traced!"],
  ["MED Soundstudio.", "Music editor deluxe!"],
  ["Hippel-COSO player.", "Jochen Hippel genius!"],
  ["TFMX format.", "CRCS music system!"],
  ["Sonix music playing.", "Unique format preserved!"],
  ["Ben Daglish tune.", "Masterwork loading!"],
  ["Rob Hubbard SID.", "Legend at work!"],
  ["Jeroen Tel SID.", "More quality incoming!"],
  ["Martin Galway tune.", "Ocean music divine!"],
  ["Tim Follin classic.", "Complexity achieved!"],
  ["David Whittaker tune.", "Prolific genius!"],
  ["Jonathan Dunn track.", "Score perfection!"],
  ["Allister Brimble tune.", "Team 17 sound!"],
  ["Bjørn Lynne track.", "Norwegian quality!"],
  ["Purple Motion module.", "Future Crew legend!"],
  ["Skaven module loaded.", "Future Crew sound!"],
  ["Jester of The Black Lotus.", "Scene legend active!"],
  ["Moby tune loaded.", "Another scene classic!"],
  ["Necros module plays.", "ACiD quality sound!"],
  ["Basehead track!", "OHC classic!"],
  ["Elwood tune playing.", "Warm scene vibes!"],
  ["Lizardking track.", "Epic chiptune!"],
  ["Superbrain module.", "Brain full of music!"],
  ["Synth4ever track.", "Synth always wins!"],
  ["Big Alec loading.", "Module master!"],
  ["Mantronix + Tip tune.", "Legends duo!"],
  ["Heatbeat module.", "Scene heat generated!"],
  ["Frequency tune playing.", "Signal perfect!"],
  ["Dune track spotted.", "Jesper Kyd vibes!"],
  ["Xeron track loading.", "Quality assured!"],
  ["Virgill composing!", "German scene master!"],
  ["LukHash electro.", "Chiptune crossover!"],
  ["Goto80 chiptune.", "Conceptual excellence!"],
  ["Bit Shifter set.", "Chiptune pioneer!"],
  ["Nullsleep tune.", "GameBoy music perfection!"],
  ["Disasterpeace track.", "Modern scene crossover!"],
  ["8bitpeoples release!", "Collective scene power!"],
  ["Demoscene: it never ends.", "The art form continues!"],
  ["One more honk for the road.", "And one more demo! :D"],
  ["Honk.", "Honk! :D"],
];
